### ISSUE TITLE
Implementar na API o CRUD de User com DjangoRest

### ISSUE THREAD

**Issue by jonathantvrs** [jackson541/API-Boletim-Covid#11]

**Comment by jackson541** [comment]
Como vai funcionar o cadastro de usuários? Forneceremos um código de verificação para que apenas pessoas selecionadas possam realizar o cadastro ou iremos fazer de outra forma?

**Comment by jonathantvrs** [comment]
Eu pensei em inserir um adm em cada cidade, fazendo isso como superuser do sistema. E aí o cadastro de usuários pode ser feito pelos admin das cidades. Para acessar as

**Comment by jonathantvrs** [comment]
Eu sei que o djangorest fornece rotas para autenticar, mas nunca utilizei, deve ser simples. Se quiser pegar a issue, assina ela pra você e dá uma olhada nisso
