### ISSUE TITLE
Faixas de Idade para cadastro de Casos

### ISSUE THREAD

**Issue by jonathantvrs** [jackson541/API-Boletim-Covid#14]
- [x] 0-20
- [x] 20-40
- [x] 40-60
- [x] 60-70
- [x] 70-80
- [x] +80

**Comment by jackson541** [comment]
Para não confundir os usuários, não seria melhor utilizar faixas nas quais o primeiro e o último valor estiverem inclusos?
Ex: 0-19, 20-39, 40-59...

**Comment by jonathantvrs** [comment]
Isso!
