### ISSUE TITLE
Requisitos Model Caso

### ISSUE THREAD

**Issue by jackson541** [jackson541/API-Boletim-Covid#15]
## TB_CASO
- id: int (chave primária)

- boletim: int (chave estrangeira -> TB_BOLETIM #8 ) (obrigatório)
- tipo: string (choices = confirmado, em tratamento, internado, recuperado, suspeito, obito, descartado, notificado) (obrigatório)
- gênero: string (choices = feminino, masculino, outro) (obrigatório)
- faixa: string (choices = #14) (obrigatório)

### Informações e questionamentos
1 - O banco PostgreSQL aceita o uso de campos com tipo array, o que permite o campo "faixa" conter um array no qual a primeira posição é o início da faixa e a segunda é o final.

2 - Sempre que um novo boletim for cadastrado nesse modelo, é preciso que as informações dos casos do boletim anterior, que foram alteradas ou não, sejam recadastradas em novos casos com o boletim recém criado associado. Dessa forma, os casos anteriores permanecem intactos e novos são criados com informações atualizadas.

3 - Seria melhor deixar apenas os campos obrigatórios no "tipo" como está e incluir campos para os opcionais nos boletins ou também adicioná-los entre as escolhas de tipos de um caso?

3 - Pensei em uma outra forma de fazer a associação entre os casos e os boletins com um relacionamento N - N. Nesse modelo, se os dados de um caso forem atualizados, cria-se um novo caso e  o associa ao novo boletim, se não, associa o mesmo caso ao novo boletim e ao anterior. Sendo assim, imagino que seja possível diminuir a uso de memória do db, já que uma linha na TB_BOLETINS_CASOS contém menos informações que uma linha na TB_CASO. No entanto, essa é uma forma que será mais trabalhosa para implementar e que talvez não traga uma grande diferença.

**Comment by jonathantvrs** [comment]
1 - Tranquilo, é isso mesmo. A faixa vai ser um select field com options que são as choices.
2 - Para não ter um retrabalho, o que se pode fazer é: se forem casos confirmados, por exemplo, vai existir a opção de dizer que esses casos são casos notificados anteriormente. O mesmo é válido para informações anteriores, ao invés de cadastrar novamente o modelo, apenas atualiza os números e o status, que é o mais viável
3 - No tipo
4 - Pode ser feito
