### ISSUE TITLE
Criar novo environment e desativar os outros

### ISSUE THREAD

**Issue by jonathantvrs** [jackson541/API-Boletim-Covid#17]
Criar environment no heroku
Desativar antigos 

Ou simplesmente pode mudar o nome de algum dos dois que estão ativos e desativar o outro.

Mas é importante deixar só um rodando

**Comment by jackson541** [comment]
Na verdade apenas uma estava rodando. Ocorreu uma duplicação quando resolvi mudar o nome da aplicação no Heroku de "covid-sjs" para "covidsjs". Após isso, procurei aqui e no heroku como remover o primeiro environment, mas não encontrei.

OBS: o segundo environment acabou de quebrar porque ela estava com deploy automático para a master.

**Comment by jonathantvrs** [comment]
Massa

**Comment by jackson541** [comment]
Me envie seu email para adicionar como colaborador no heroku.

**Comment by jonathantvrs** [comment]
jontvrs@gmail.com
