### ISSUE TITLE
Criação das demais branchs

### ISSUE THREAD

**Issue by jackson541** [jackson541/API-Boletim-Covid#19]
No padrão antigo, eu estava utilizando apenas uma branch de desenvolvimento sem seguir a risca o padrão do Gitflow. Acho que agora seguir esse padrão, com a criação das branchs de features e as demais, será o ideal. Tem outra ideia em mente ou prefere seguir por essa, @jonathantvrs ?

**Comment by jonathantvrs** [comment]
Exatamente isso, cada feature, seja ela funcionalidade, ajuste ou correção de bug, BRANCH nela. E o ideal é que elas recebam o nome completo da funcionalidade e um número antes que é justamente o número da issue.
