### ISSUE TITLE
Desenvolvimento orientado a testes

### ISSUE THREAD

**Issue by jackson541** [jackson541/API-Boletim-Covid#23]
Esqueci de perguntar antes, mas quer seguir o desenvolvimento utilizando os testes? Nunca trabalhei com testes, mas sei como eles funcionam, pelo menos em JS. Até agora só fiz os testes da api manualmente.

**Comment by jonathantvrs** [comment]
Fala de TDD? Acho que por enquanto não, daria muito trabalho e precisamos ganhar tempo. Mas podemos automatizar com Testes unitários depois da feature ser implementada

**Comment by jackson541** [comment]
Sim. Mas, até agora, só sei como funcionam os testes unitários kkk

**Comment by jonathantvrs** [comment]
Tranquilo! o ideal é fazermos primeiro os unitários

**Comment by jonathantvrs** [comment]
Depois nós podemos utilizar o Selenium para automatizar testes de sistema, por exemplo

**Comment by jackson541** [comment]
show
