### ISSUE TITLE
Exclusão de Usuário

### ISSUE THREAD

**Issue by jonathantvrs** [jackson541/API-Boletim-Covid#28]
@jackson541 , tava vendo aqui os modelos e se não me falha a memória, o ondelete CASCADE deleta a referência na tabela filha, logo acho que ao deletar um usuário de uma cidade, a cidade também será deletada.

**Comment by jonathantvrs** [comment]
Ou seria o contrário?

**Comment by jackson541** [comment]
Na verdade é ao contrário. Deletar uma cidade faz com que todos os usuários relacionados sejam deletados. Isso pq a referência está na tabela de usuários.

**Comment by jonathantvrs** [comment]
Eu acho que uma boa pratica na verdade seria a adesão de um campo chamado ativo em todas as entidades, com default true. Acho que remover uma cidade, deveria inativar todos os users e não perdê-los também. Isso vale para as outras entidades. O que de fato vai ser feito num DELETE é um UPDATE setando ativo para false

**Comment by jonathantvrs** [comment]
o que acha?

**Comment by jackson541** [comment]
É uma ótima ideia, vários outros projetos seguem esse padrão. Vou implementar nessa branch de crud de usuario junto com as demais modificações
