### ISSUE TITLE
Adicionar atributo ativo em todas as entidades do sistema

### ISSUE THREAD

**Issue by jonathantvrs** [jackson541/API-Boletim-Covid#30]
Com o atributo ativo implementado, é preciso fazer uma alteração no método delete, para que o o sistema não delete o registro do banco, apenas faça o update de ativo para false. Também é necessário adicionar em todas as listagens que somente os dados com ativo true sejam mostrados no sistema, é só colocar um filtro nos serializers

**Comment by jackson541** [comment]
Os administradores das cidades (aqueles que nós cadastramos no sistema) devem ter permissão para "deletar" a cidade?

**Comment by jonathantvrs** [comment]
Não! As cidades são invioláveis. Só que adiciona e retira somos nós

**Comment by jackson541** [comment]
Procurei, mas não encontrei uma forma de colocar o filtro diretamente no serializer. Então, irei ver se consigo aplicar os filtros nos generics views passando eles para mixins.

**Comment by jonathantvrs** [comment]
Está bem
