### ISSUE TITLE
Criar Testes unitários para Usuário 

### ISSUE THREAD

**Issue by jonathantvrs** [jackson541/API-Boletim-Covid#31]

**Comment by jackson541** [comment]
Vamos utilizar o selenium para os testes?

**Comment by jackson541** [comment]
O Django Rest aprensenta uma [seção para testes](https://www.django-rest-framework.org/api-guide/testing/). Acho que o Selenium não é feito para testes de API.

**Comment by jonathantvrs** [comment]
Sim, o selenium será para quando tivermos o front
