### ISSUE TITLE
Criar permissão personalizada para CRUD de Cidade

### ISSUE THREAD

**Issue by jackson541** [jackson541/API-Boletim-Covid#35]
O Django Rest não fornece um tipo de permissão que apenas superusuários tenham acesso

**Comment by jackson541** [comment]
@jonathantvrs  Isso ou podemos deixar apenas as rotas de list e view para as cidades e fazer a criação, atualização e deletar pelo Django admin.

**Comment by jonathantvrs** [comment]
Pode ser, é o caminho mais simples!
