### ISSUE TITLE
Separar funções

### ISSUE THREAD

**Issue by jackson541** [jackson541/API-Boletim-Covid#39]
Se as funções da View.py forem separadas em arquivos de tipo de entidade e importadas de volta na View, irá continuar funcionando? O arquivo está ficando muito grande

**Comment by jonathantvrs** [comment]
Funciona sim! Mas eu acho que por enquanto não é necessário. Temos que pensar numa forma de refatorar e deixar mais clean

**Comment by jonathantvrs** [comment]
Mas talvez seja melhor separar essas funções em um arquivo chamado utils.py, já que eles não fazem parte diretamente da regra de negócio

**Comment by jackson541** [comment]
as funções de verificação ou todas?

**Comment by jonathantvrs** [comment]
Verificação.

**Comment by jackson541** [comment]
show
