### ISSUE TITLE
Adicionar possibilidade de enviar o token ou logar no Swagger 

### ISSUE THREAD

**Issue by jonathantvrs** [jackson541/API-Boletim-Covid#47]
Importante possibilitar isso, deixa todas as rotas abertas mas exige token para aquelas que precisam

**Comment by jonathantvrs** [comment]
Ou então, ao invés disso, pode implementar para funcionar com as credenciais e adicionar no swagger as cidades. Acho mais interessante

**Comment by jackson541** [comment]
Na verdades as demais rotas de cidades não existem, elas só podem ser executadas pelo django admin. #35

**Comment by jackson541** [comment]
Não entendi bem o que você está pedindo. As verificações já foram adicionadas a todas as rotas, imagino que estejam corretas. Além disso, pelo que testei agora, não da para fazer as requisições que exigem autorização pelo modelo do swagger que está na api, porque ele não fornece um campo para adicionar o Token ao cabeçalho.

**Comment by jackson541** [comment]
Por algum motivo, a rota de token não está exibindo os campos username e password obrigatórios. Isso acontece porque o swagger está se baseando nos Models da API?

![image](https://user-images.githubusercontent.com/40877357/87428487-ca7c0080-c5b8-11ea-9549-eb14b9402ddf.png)

**Comment by jonathantvrs** [comment]
Exato. Tem que ver na documentação da lib ou então na própria documentação do swagger, acredito que seja porque tem que documentar bem direitinho, não sei se você viu mas tem uma descrição que ele pega de uma documentação que foi feita por você lá no código, só não lembro qual exatamente.

**Comment by jonathantvrs** [comment]
Por isso a issue #44 é essencial

**Comment by jackson541** [comment]
Ainda não conheço o padrão, mas vou já procurar por ele.

**Comment by jonathantvrs** [comment]
é o PEP 08, bem simples de encontrar. Qualquer coisa é só procurar um repositório opensource de python que  com certeza eles utilizam documentação no padrão

**Comment by jackson541** [comment]
Aaaah homi kkkk. Eu conhecia, só não lembrava pelo nome

**Comment by jackson541** [comment]
Mas eu realmente esqueço de seguir algumas coisas, como o limite de caracteres por linha e espaçamento. Vou olhar todas as regras do padrão e ajeitar
