### ISSUE TITLE
Falha em testes unitários 

### ISSUE THREAD

**Issue by jonathantvrs** [jackson541/API-Boletim-Covid#50]
Rodei os testes localmente e recebi 6 falhas e 11 erros dos 22 testes feitos.

**Comment by jackson541** [comment]
Provavelmente é porque os teste não foram atualizados após a criação do modelo Boletim

**Comment by jackson541** [comment]
Na verdade o que está fazendo a maioria dos testes dar erro é a troca do db. Vou ver como ajeitar.

**Comment by jackson541** [comment]
Ele não está apagando os registros no banco de dados entre um teste e outro, sabe como resolver?

**Comment by jonathantvrs** [comment]
Sei sim. Tem algumas formas de se resolver esse problema, uma é apagando todos os registros do banco (menos indicada) e a outra é com [Mocks](https://www.toptal.com/python/an-introduction-to-mocking-in-python) (mais indicada).

**Comment by jackson541** [comment]
show, vou adiantar logo a parte do modelo de boletim e após isso ver como utilizar os mocks.

**Comment by jackson541** [comment]
@jonathantvrs pelo que entendi, o mock serve para simular uma resposta do banco de dados para uma função quando ela é chamada? (ex: simula os boletins retornados em um GET)

**Comment by jonathantvrs** [comment]
É por aí. Basicamente eles não utilizam os métodos originais mas devolvem pro teste aquilo que é necessário

**Comment by jackson541** [comment]
Então eles não fazem a requisição para as funções do sistema?

**Comment by jonathantvrs** [comment]
Eles utilizam sim, mas eles criam meio que uma instância fake dos serializers por exemplo, para testá-los

**Comment by jonathantvrs** [comment]
É complicado de entender assim mas ao fazer os testes você vai entendendo

**Comment by jonathantvrs** [comment]
[O que é um MOCK?](https://pt.wikipedia.org/wiki/Objeto_Mock)

**Comment by jackson541** [comment]
Aah entendi

**Comment by jonathantvrs** [comment]
Eu utilizo mocks num projeto que fiz em Spring. Se quiser dar uma olhada eu te adiciono lá, está privado

**Comment by jonathantvrs** [comment]
É em Java mas a ideia é a mesma

**Comment by jackson541** [comment]
Adicione, assim uso como exemplo na hora de criar

**Comment by jonathantvrs** [comment]
Mas de qualquer forma, dá uma lida no link lá que mandei do wikipedia, ele é muito bom.

**Comment by jackson541** [comment]
Beleza, eu li o começo que foi o que me fez entender mais

**Comment by jackson541** [comment]
@jonathantvrs entendi a proposta dos mocks, porém percebi que existe uma maneira que pode ser mais fácil para realizar os testes. O problema mesmo é que o banco de dados está deletando os registros dos testes, mas não reinicia a contagem de ID dos objetos entre um teste e outro. Então, posso utilizar os registros que foram recém criados para os testes. O que acha?

**Comment by jonathantvrs** [comment]
Se ele cobre os testes, então beleza.
