### ISSUE TITLE
Refatoração dos casos e boletins

### ISSUE THREAD

**Issue by jackson541** [jackson541/API-Boletim-Covid#53]
## Boletim model
* id: int (chave primária) (definido pelo sistema)

* cidade: int (chave estrangeira) (obrigatório)

* data: datetime (obrigatório)

* ativo: boolean (definido pelo sistema)

* casosConfirmados: int (obrigatório)

* casosEmTratemento: int (obrigatório)

* casosInternados: int (obrigatório)

* casosRecuperados: int (obrigatório)

* casosSuspeitos: int (obrigatório)

* casosDeObito: int (obrigatório)

* casosDescartados: int (obrigatório)

* casosNotificados: int (obrigatório)

## InformacoesCasos
* id: int (chave primária) (definido pelo sistema)

* cidade: int (chave estrangeira) (obrigatório)

* data: datetime (obrigatório)

* ativo: boolean (definido pelo sistema)

## CasosConfirmados (e demais tipos de casos)
* id: int (chave primária) (definido pelo sistema)

* informacoesCasos: int(chave estrangeira) (obrigatório)

* ativo: boolean (definido pelo sistema)

* masculino: int (obrigatório)

* feminino: int (obrigatório)

* outro: int (obrigatório)

* faixa_0_19: int (obrigatório)

* faixa_20_39: int (obrigatório)

* faixa_40_59: int (obrigatório)

* faixa_60_69: int (obrigatório)

* faixa_70_79: int (obrigatório)

* faixa_80: int (obrigatório)

**Comment by jonathantvrs** [comment]
@jackson541 tudo ótimo, só que ainda não gostei de todos esses campos de faixa de idade. O que você acha de reproduzir o diagrama de entidades no draw.io e encontrar uma solução viável pra isso? Acho que vendo o todo fica mais simples

**Comment by jackson541** [comment]
Também não gostei. Depois pensei em outro modelo, mas também não é viável.

**Comment by jackson541** [comment]
https://drive.google.com/file/d/1NCsgQZ2qJxgUsnBWRN0qK-rGgs6IrfDC/view?usp=sharing

**Comment by jonathantvrs** [comment]
Pode ver que todas as entidades de casos são iguais. Podemos generalizar, colocando um campo com o tipo dela

**Comment by jackson541** [comment]
Realmente

**Comment by jackson541** [comment]
@jonathantvrs consegue ver as alterações?

**Comment by jonathantvrs** [comment]
Consigo sim. Mas acho que ainda dá pra melhorar. Estou pensando nisso agora. Me dá permissão em jontvrs@gmail.com
