### ISSUE TITLE
Bug: Deploy Heroku

### ISSUE THREAD

**Issue by jonathantvrs** [jackson541/API-Boletim-Covid#59]
O deploy está funcionando? Aparentemente não. E ainda tem dois environments no repo, fico confuso. Precisamos trocar os nomes também. O ideal é criar um novo

**Comment by jackson541** [comment]
Realmente está dando erro. Atualmente está nesse endereço: https://apiboletimcovid.herokuapp.com/

**Comment by jackson541** [comment]
Amanhã vou ajeitar

**Comment by jonathantvrs** [comment]
Tranquilo!
