### ISSUE TITLE
Analisar Boletins de Covid-19 das cidades de Caicó, Jucurutu, São João do Sabugi e outras

### ISSUE THREAD

**Issue by jonathantvrs** [jackson541/API-Boletim-Covid#6]
Com a análise:

- [x] Anexar imagens dos boletins nessa issue
- [x] Escrever os requisitos do modelo Boletim em #8  
- [x] Escrever os requisitos do modelo Cidade em #9 

[Lista de cidades](https://pt.wikipedia.org/wiki/Serid%C3%B3_(Rio_Grande_do_Norte))

**Comment by jackson541** [comment]
Boletim atual - São João do Sabugi
![image](https://user-images.githubusercontent.com/40877357/85625105-4bdb1580-b641-11ea-9cc3-7f4f7cbbafbf.png)

**Comment by jonathantvrs** [comment]
![image](https://user-images.githubusercontent.com/9680493/85625849-77aacb00-b642-11ea-978b-b579d71511d6.png)

**Comment by jonathantvrs** [comment]
![image](https://user-images.githubusercontent.com/9680493/85626502-86de4880-b643-11ea-877e-b35e940cf242.png)

**Comment by jackson541** [comment]
![image](https://user-images.githubusercontent.com/40877357/85626844-053aea80-b644-11ea-92b4-0f8dfd5bba05.png)

**Comment by jonathantvrs** [comment]
![image](https://user-images.githubusercontent.com/9680493/85626859-09ff9e80-b644-11ea-825f-964db5248b09.png)

**Comment by jackson541** [comment]
![image](https://user-images.githubusercontent.com/40877357/85626977-35828900-b644-11ea-8db7-9b7803f2bf39.png)

**Comment by jackson541** [comment]
![image](https://user-images.githubusercontent.com/40877357/85627202-8abe9a80-b644-11ea-8671-d0ecb0b5c84d.png)

**Comment by jackson541** [comment]
![image](https://user-images.githubusercontent.com/40877357/85627405-ceb19f80-b644-11ea-8ffd-b62c562caccc.png)
OBS: esse de jardim é mais detalhado, contendo faixa etária e sexo
