### ISSUE TITLE
Relacionar cidade do usuário criado com a do criador

### ISSUE THREAD

**Issue by jackson541** [jackson541/API-Boletim-Covid#64]
Enquanto fazia a tela de usuários, percebi que a API está pedindo, como entrada para criar um usuário, username, password e cidade. Porém, a cidade do usuário criado deve ser a mesma do seu criador.

**Comment by jonathantvrs** [comment]
Isso, faz total sentido!

**Comment by jonathantvrs** [comment]
É simples de resolver

**Comment by jonathantvrs** [comment]
Deixa a cidade e seta o atributo na criação
