### ISSUE TITLE
Adicionar Badge de Deploy Heroku no README 

### ISSUE THREAD

**Issue by jonathantvrs** [jackson541/API-Boletim-Covid#65]
Configurar integração contínua e ver a possibilidade de ser feito junto com a issue #45

**Comment by jackson541** [comment]
Ele estar com deploy automático no heroku já não conta como CI?

**Comment by jonathantvrs** [comment]
Então temos que colocar o badge no README.md

**Comment by jonathantvrs** [comment]
#16

**Comment by jonathantvrs** [comment]
@jackson541 vê como colocar o badge de deploy do heroku pra matar essa task logo

**Comment by jackson541** [comment]
blz

**Comment by jackson541** [comment]
![image](https://user-images.githubusercontent.com/40877357/89082144-7bc5b900-d363-11ea-8c4a-8532e7eb794f.png)

@jonathantvrs o que acha desse? Eu achei bonito, mas fora do padrão tbm kkkk

**Comment by jackson541** [comment]
![image](https://user-images.githubusercontent.com/40877357/89082788-6ea9c980-d365-11ea-96b8-4c995e0f0c46.png)


Tem esses outros dois, mas o menor é meio bugado pq tenho que colocar um app diferente pra ele aparecer que o deploy funcionou.

**Comment by jonathantvrs** [comment]
Coloca o primero mesmo
