### ISSUE TITLE
Alterar autenticação com Token

### ISSUE THREAD

**Issue by jackson541** [jackson541/API-Boletim-Covid#68]
[Esse artigo](https://medium.com/@yerkebulan199/django-rest-framework-drf-token-authentication-with-expires-in-a05c1d2b7e05) é bem interessante. O token registra tbm a data em que foi criado, então é possível estipular um tempo de validade.

**Comment by jackson541** [comment]
![image](https://user-images.githubusercontent.com/40877357/88461829-6e00c700-ce7d-11ea-95a8-48a92f9af317.png)

**Comment by jonathantvrs** [comment]
Ótimo

**Comment by jackson541** [comment]
@jonathantvrs quando o token expirar, o usuário deve ser redirecionado para o login?

**Comment by jonathantvrs** [comment]
Isso, é interessante que sim

**Comment by jackson541** [comment]
Eu testei esse mesmo código do artigo no projeto e funcionou bem, algum problema com a gente utilizar ele?

**Comment by jonathantvrs** [comment]
Não, tá ótimo!
