### ISSUE TITLE
Adicionar CORS

### ISSUE THREAD

**Issue by jackson541** [jackson541/API-Boletim-Covid#70]
A aplicação (no heroku) está negando as requisições do Front, mas achei estranho que não está negando as requisições que faço pelo Postman. [django cors](https://github.com/adamchainz/django-cors-headers)

**Comment by jonathantvrs** [comment]
É questão de cors mesmo

**Comment by jonathantvrs** [comment]
Tem que habilitar o cors para o dominio do heroku
