### ISSUE TITLE
Problema na listagem de boletins

### ISSUE THREAD

**Issue by jackson541** [jackson541/API-Boletim-Covid#73]
A rota de listagem geral deve receber uma query para definir a cidade de retorno dos boletins. Atualmente todos são retornados.

**Comment by jonathantvrs** [comment]
Massa, o fluxo então vai ser Logar -> pega a cidade do user e faz a requisição com filtro e carrega no componente. Acho que daria pra fazer direto no front não?

**Comment by jackson541** [comment]
Na vdd tem que ser tanto aqui como lá pq a rota de boletins ainda não faz o filtro por cidade

**Comment by jackson541** [comment]
E também tem que alterar a rota de listar um usuário para ele filtrar por username.

**Comment by jonathantvrs** [comment]
Ok!
