### ISSUE TITLE
Requisitos Model Boletim

### ISSUE THREAD

**Issue by jonathantvrs** [jackson541/API-Boletim-Covid#8]
Com base na issue #6

**Comment by jackson541** [comment]
nome: tipo (opcional/obrigatório)

## TB_BOLETIM
- id: int (chave primária) (obrigatório)
- cidade: string (chave estrangeira -> TB_CIDADE) (obrigatório)
- data: date (obrigatório)

- casosConfirmados: int (obrigatório)
- casosEmTratamento: int _(opcional)_
- casosInternados: int _(opcional)_
- casosRecuperados: int (obrigatório)
- casosSuspeitos: int (obrigatório)
- casosDeObito: int (obrigatório)
- casosDescartados: int (obrigatório)
- casosNotificados: int _(opcional)_

**Comment by jonathantvrs** [comment]
Excellent

**Comment by jonathantvrs** [comment]
@jackson541 temos que pensar em como vamos representar um Caso, acredito que tem ser uma entidade e por isso vamos ter que remodelar parte do que foi pensado. O Caso seria para registrar se é homem ou mulher, a idade e se é um caso confirmado, suspeito, notificado ou de óbito. Alguma ideia? Eu pensei que poderíamos possibilitar o registro de cada caso e os campos casosNotificados, casosDeObito, ... poderiam ser atributos derivados no Boletim. O que acha?

**Comment by jackson541** [comment]
@jonathantvrs É uma excelente ideia, mas isso leva em conta que o usuário irá cadastrar apenas os casos novos de cada tipo (ex: +1 caso confirmado e +2 casos recuperados) ou que ele vai cadastrar todos os casos registrados como está no modelo atual? Da primeira forma é viável porque serão poucos casos para adicionar gênero, idade e o tipo de caso. Para adicionar todos os casos, como no modelo atual, se torna algo complicado. Ou a ideia desse registro de caso é de outra forma?

**Comment by jonathantvrs** [comment]
Que vai ser cadastrado caso a caso ou um grupo de casos de uma vez.

**Comment by jonathantvrs** [comment]
Mas vamos trabalhar com caso a caso, inicialmente.

**Comment by jackson541** [comment]
Junto com o boletim, também devem ser retornados todos os casos relacionados a ele, correto?

**Comment by jonathantvrs** [comment]
Cada Caso não, somente os números.

**Comment by jackson541** [comment]
show

**Comment by jackson541** [comment]
Um campo do tipo DateField já não contemplaria o boletim? Acredito que com esse campo torne mais simples gerar os dados dos gráficos.

**Comment by jonathantvrs** [comment]
Acho melhor o DateTime, porque mostra a hora em que o boletim foi postado. Como diz o ditado: "Melhor pecar pelo excesso" kk
