### ISSUE TITLE
Requisitos Model Cidade

### ISSUE THREAD

**Issue by jackson541** [jackson541/API-Boletim-Covid#9]
## TB_CIDADE

- id: int (chave primária)
- nome: string (chave candidata ou única) (obrigatório)
- responsável: int (chave estrangeira -> User) (obrigatório)
- numeroHabitantes: int (obrigatório)

**Comment by jonathantvrs** [comment]
Excellent!

**Comment by jackson541** [comment]
Porque o nome não pode ser a chave primária, já que um estado não tem mais de uma cidade com o mesmo nome?

**Comment by jonathantvrs** [comment]
Poder pode, mas não é uma boa prática colocar string como chave primária! Vai variar de negócio pra negócio mas o ideal é sempre usar um id mesmo

**Comment by jonathantvrs** [comment]
É mais simples referenciar um id do que um nome
